### ISSUE TITLE
Typo should be fixed in Part 6

### ISSUE THREAD

**Issue by pisymbol** [udacity/DL_PyTorch#2]
Under the subheading "Saving and loading networks" there is a sentence:

`The simplest thing to do is simply save the state **** with torch.save. For example, we can save it to a file 'checkpoint.pth'.`

I'm going to out on a limb and say you wanted to type "dict" with a T not a K.

**Comment by mcleonard** [comment]
Sigh, yes. Thanks for spotting that

**Comment by mcleonard** [comment]
Fixed in https://github.com/udacity/DL_PyTorch/commit/dc8b7c2143f1911fc75b9893c5d253d1a1061130

**Comment by pisymbol** [comment]
It made my day at least Mat. So there is that. Thanks.
